version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-booking-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - event-booking

  nginx:
    image: nginx:alpine
    container_name: event-booking-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - event-booking

  db:
    image: mysql:8.0
    container_name: event-booking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - event-booking

networks:
  event-booking:
    driver: bridge
